armada/urls.py
# coding: utf8

from django.conf.urls import url
from . import views


app_name = 'armada'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),

    url(r'^news/(?P<slug>[-_\w]+)/$', 'armada.views.news_detail_view', name='news_detail'),

    url(r'^blog/(?P<slug>[-_\w]+)/$', 'armada.views.blog_detail_view', name='blogs_detail'),
    url(r'^news/', 'armada.views.news_list_view', name='news_list'),
    url(r'^blog/', 'armada.views.blog_list_view', name='blogs_list'),
    url(r'^contact/', views.contact, name='contact'),



]

armadaLocal/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^feedback/', include('backcall.urls')),
    url(r'^', include('armada.urls')),
    url(r'^uslugi/', include('services.urls')),
    url(r'^zakonodatelsvo/', include('law.urls')),
    url(r'^magazin/', include('shop.urls')),
    url(r'^sozdanie-sajta/', include('sitecreate.urls')),
    url(r'^portfolio/', include('portfolio.urls')),

]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

law/urls.py
# coding: utf8

from django.conf.urls import url
from . import views
app_name = 'law'

urlpatterns = [
    url(r'^$', views.index , name = 'index_law'),
]

armada/models.py
# coding: utf8
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from froala_editor.fields import FroalaField
from django.db import models
from blog.models import Blog
from news.models import News
from law.models import Article
from services.models import About

# Create your models here.

class About(models.Model):
    title = models.CharField(verbose_name = _('Title'), max_length = 255)
    slug = models.SlugField(max_length = 55, verbose_name = _('Url'))
    image = models.ImageField(verbose_name = _('Image'), upload_to = 'uploads/armada/about')
    text = FroalaField(verbose_name = _('Text'))

    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'about'
        verbose_name = _('About')
        verbose_name_plural = _('About')

class Social(models.Model):
    title = models.CharField(verbose_name = _('Title'), max_length = 255)
    image = models.ImageField(verbose_name = _('Image'), upload_to = 'uploads/armada/social')
    url = models.CharField(verbose_name = _('Url'), max_length = 255)

    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'social'
        verbose_name = _('Social')
        verbose_name_plural = _('Socials')

class Contact(models.Model):
    title = models.CharField(verbose_name = _('Title'), max_length = 255)
    image = models.ImageField(verbose_name = _('Image'), blank = True, null = True, upload_to = 'uploads/armada/contact')
    phone = models.CharField(verbose_name = _('Phone number'),max_length = 255, default = 0)


    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'contact'
        verbose_name = _('Contact')
        verbose_name_plural = _('Contacts')

class Address(models.Model):
    title = models.CharField(verbose_name = _('Title'), max_length = 255)
    address = models.CharField(verbose_name = _('Address'),max_length = 255, default = 0)


    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'address'
        verbose_name = _('Address')
        verbose_name_plural = _('Addresses')

class Review(models.Model):
    title = models.CharField(verbose_name = _('Title'), max_length = 255)
    company = models.CharField(verbose_name = _('Company'), max_length = 255)
    text = models.TextField()

    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'review'
        verbose_name = _('Review')
        verbose_name_plural = _('Reviews')

class Offer(models.Model):
    title = models.CharField(verbose_name= _('Title'), max_length = 255)
    image = models.ImageField(verbose_name = _('Image'), blank = True, null = True, upload_to = 'uploads/armada/offer')
    text = models.TextField(verbose_name = _('Text'))

    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'offer'
        verbose_name = _('Offer')
        verbose_name_plural = _('Offers')


class FooterInfo(models.Model):
    title = models.CharField(verbose_name = _('Title'), max_length = 250, default = '')
    image = models.ImageField(verbose_name = _('Logo'), upload_to = 'uploads/armada/footer')
    text = FroalaField(verbose_name = _('Text'))
    created = models.CharField(verbose_name = _('Created Date'), max_length = 250)
    created_by = models.CharField(verbose_name = _('Created By'), max_length = 100)
    logo = models.ImageField(verbose_name = _('Goog Studio logo'), upload_to = 'uploads/armada/goog_logo')

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = _('footer info')
        verbose_name_plural = _('Footer Info')


class GlobalMeta(models.Model):
    title = models.CharField(max_length=55, default=None, help_text="Для указания локальной мета-информации на странице всех новостей укажите здесь 'News', для страницы всех блогов 'Blog', для страницы контактов 'Contacts' ")
    meta_title = models.CharField(max_length = 100, verbose_name = _('Мета header'), blank = True)
    meta_desc = models.TextField(verbose_name = _('Мета description'), blank = True)
    meta_key = models.CharField(max_length = 200, verbose_name = ('Мета keywords'), blank = True)

    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'Globalmeta'
        verbose_name = _('Meta')
        verbose_name_plural = _('Metas')


class LocalMeta(models.Model):
    meta_title = models.CharField(max_length = 100, verbose_name = _('Мета header'), blank = True)
    meta_desc = models.TextField(verbose_name = _('Мета description'), blank = True)
    meta_key = models.CharField(max_length = 200, verbose_name = ('Мета keywords'), blank = True)
    blog = models.ForeignKey(Blog, related_name="blog", blank=True, null=True)
    news = models.ForeignKey(News, related_name="news", blank=True, null=True)
    service = models.ForeignKey(About, related_name='service', blank=True, null=True)

    def __unicode__(self):
        return self.meta_title

    class Meta:
        db_table = 'Localmeta'
        verbose_name = _('lMeta')
        verbose_name_plural = _('lMetas')

client/models.py
# coding: utf8
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.db import models

# Create your models here.
class Client(models.Model):
    name = models.CharField(verbose_name = _('Title'), max_length = 255)
    image = models.ImageField(verbose_name = _('Image'), upload_to = 'uploads/client')
    url = models.CharField(verbose_name = _('Url'), max_length = 255)

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'clients'
        verbose_name = _('Client')
        verbose_name_plural = _('Clients')

news/models.py
# coding: utf-8
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.db import models
from froala_editor.fields import FroalaField

# Create your models here.
class News(models.Model):
    title = models.CharField(max_length = 100, verbose_name = _('Title'))
    slug = models.SlugField(max_length = 55, verbose_name = _('Slug'), blank = True, unique=True)
    image = models.ImageField(upload_to= 'uploads/news/images',verbose_name =_('Image'), default = False)
    text = FroalaField(verbose_name = _('Text'))
    shown = models.IntegerField(default = 0, verbose_name = _('Views'), editable = False)
    created = models.DateTimeField(auto_now_add = True, verbose_name = _('Publication date'))


    class Meta:
        db_table = 'news'
        verbose_name = _('News')
        verbose_name_plural = _('News')

    def __unicode__(self):
        return self.title

armada/views.py
#coding: utf8


from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, render_to_response
from django.template.context_processors import csrf
from django.views import generic
# local
from client.models import Client
from news.models import News
from blog.models import Blog
from armada.models import *
from slider.models import Slider
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404

# Create your views here.


def blog_list_view(request, context={}):
    context.update(csrf(request))
    blog_list = Blog.objects.all().order_by('-created')
    context['contacts'] = Contact.objects.all()
    context['addresses'] = Address.objects.all()
    context['finfo'] = FooterInfo.objects.get()
    context['lmeta'] = GlobalMeta.objects.filter(title="Blog")
    context['gmeta'] = GlobalMeta.objects.filter(title="Global")
    paginator = Paginator(blog_list, 4)
    page = request.GET.get('page')

    try:
        blog = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        blog = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        blog = paginator.page(paginator.num_pages)

    context['blog'] = blog
    return render_to_response('blogs/list.html', context)

def blog_detail_view(request, context={}, slug=""):
    context.update(csrf(request))
    context['contacts'] = Contact.objects.all()
    context['addresses'] = Address.objects.all()
    context['finfo'] = FooterInfo.objects.get()
    context['gmeta'] = GlobalMeta.objects.all()
    context['lmeta'] = LocalMeta.objects.filter(blog__slug=slug)
    context['gmeta'] = GlobalMeta.objects.filter(title="Global")
    context['blog'] = Blog.objects.get(slug=slug)
    return render_to_response('blogs/detail.html', context)


def news_detail_view(request, context={}, slug=""):
    context.update(csrf(request))
    context['news'] = News.objects.get(slug=slug)
    context['contacts'] = Contact.objects.all()
    context['addresses'] = Address.objects.all()
    context['finfo'] = FooterInfo.objects.get()
    context['lmeta'] = LocalMeta.objects.filter(news__slug=slug)
    context['gmeta'] = GlobalMeta.objects.filter(title="Global")
    context['socials'] = Social.objects.all()
    return render_to_response("news/detail.html", context)


def news_list_view(request, context={}):
    context.update(csrf(request))
    news_list = News.objects.all().order_by('-created')
    context['contacts'] = Contact.objects.all()
    context['addresses'] = Address.objects.all()
    context['finfo'] = FooterInfo.objects.get()
    context['socials'] = Social.objects.all()
    context['lmeta'] = GlobalMeta.objects.filter(title="News")
    context['gmeta'] = GlobalMeta.objects.filter(title="Global")
    paginator = Paginator(news_list, 4)
    page = request.GET.get('page')

    try:
        news = paginator.page(page)
    except PageNotAnInteger:
    # If page is not an integer, deliver first page.
        news = paginator.page(1)
    except EmptyPage:
    # If page is out of range (e.g. 9999), deliver last page of results.
        news = paginator.page(paginator.num_pages)

    context['news'] = news
    return render_to_response('news/list.html', context)


def index(request, context = {}):

    try:
        clients = Client.objects.all()
    except Client.DoesNotExist:
        clients = False
    context['clients'] = clients
    try:
        news = News.objects.all().order_by('-created')[:2]
    except News.DoesNotExist:
        news = False
    context['news'] = news
    try:
        blog = Blog.objects.all().order_by('-created')[:2]
    except Blog.DoesNotExist:
        blog = False
    context['blogs'] = blog
    try:
        contact = Contact.objects.all()
    except Contact.DoesNotExist:
        contact = False
    context['contacts'] = contact
    try:
        social = Social.objects.all()
    except Social.DoesNotExist:
        social = False
    context['socials'] = social
    try:
        address = Address.objects.all()
    except Address.DoesNotExist:
        address = False
    context['addresses'] = address
    try:
        about = About.objects.get(slug = 'o-nas')
    except About.DoesNotExist:
        about = False
    context['about'] = about
    try:
        answer = About.objects.get(slug = 'pochemu-my')
    except About.DoesNotExist:
        answer = False
    context['answer'] = answer
    try:
        slider = Slider.objects.all()
    except Slider.DoesNotExist:
        slider = False
    context['sliders'] = slider
    try:
        review = Review.objects.all()
    except Review.DoesNotExist:
        review = False
    context['reviews'] = review
    context['title'] = 'Main'
    try:
        offer = Offer.objects.all()
    except Offer.DoesNotExist:
        offer = False
    context['offers'] = offer
    try:
        finfo = FooterInfo.objects.get()
    except FooterInfo.DoesNotExist:
        finfo = False
    context ['finfo'] = finfo
    try:
       context['gmeta'] = GlobalMeta.objects.filter(title="Global")
    except GlobalMeta.DoesNotExist:
       globalmeta = False

    return render(request, 'armada/index.html', context)


# class NewsListView(generic.ListView):
#     model = News
#     template_name = 'news/list.html'
#     context_object_name = 'news'
#
#     def get_context_data(self, *args, **kwargs):
#         context = super(NewsListView, self).get_context_data(**kwargs)
#         news_list = News.objects.all().order_by('-created')
#         context['contacts'] = Contact.objects.all()
#         context['addresses'] = Address.objects.all()
#         context['finfo'] = FooterInfo.objects.get()
#         context['lmeta'] = GlobalMeta.objects.filter(title="News")
#         context['gmeta'] = GlobalMeta.objects.filter(title="Global")
#         paginator = Paginator(news_list, 1)
#         page = request.GET.get('page')
#
#         try:
#             news = paginator.page(page)
#         except PageNotAnInteger:
#         # If page is not an integer, deliver first page.
#             news = paginator.page(1)
#         except EmptyPage:
#         # If page is out of range (e.g. 9999), deliver last page of results.
#             news = paginator.page(paginator.num_pages)
#
#         context['news'] = news
#         return context

# class NewsDetailView(generic.DetailView):
#     model = News
#     template_name = 'news/detail.html'
#     context_object_name = 'news'
#
#     def get_context_data(self, *args, **kwargs):
#         context = super(NewsDetailView, self).get_context_data(**kwargs)
#         context['news'] = News.objects.get(slug = kwargs['object'].slug)
#         context['contacts'] = Contact.objects.all()
#         context['addresses'] = Address.objects.all()
#         context['finfo'] = FooterInfo.objects.get()
#
#         return context


# class BlogListView(generic.ListView):
#     model = Blog
#     template_name = 'blogs/list.html'
#     context_object_name = 'blogs'
#
#     def get_context_data(self, *args, **kwargs):
#         context = {}
#         context['blogs'] = Blog.objects.all().order_by('-created')
#         context['contacts'] = Contact.objects.all()
#         context['addresses'] = Address.objects.all()
#         context['finfo'] = FooterInfo.objects.get()
#         context['lmeta'] = GlobalMeta.objects.filter(title="Blog")
#         context['gmeta'] = GlobalMeta.objects.filter(title="Global")
#
#         return context


# class BlogDetailView(generic.DetailView):
#     model = Blog
#     template_name = 'blogs/detail.html'
#     context_object_name = 'blog'
#
#     def get_object(self, queryset=None):
#         return get_object_or_404(Blog, slug = self.kwargs.get('slug'))
#         context['contacts'] = Contact.objects.all()
#         context['addresses'] = Address.objects.all()
#         context['finfo'] = FooterInfo.objects.get()
#         context['gmeta'] = GlobalMeta.objects.get()
#         context['lmeta'] = LocalMeta.objects.get()
#
#
#         return context

def contact(request, context = {}):
    try:
        contact = Contact.objects.all()
    except Contact.DoesNotExist:
        contact = False
    context ['contacts'] = contact
    context['contacts'] = Contact.objects.all()
    context['offers'] = Offer.objects.all()
    context['socials'] = Social.objects.all()
    context['addresses'] = Address.objects.all()
    context['finfo'] = FooterInfo.objects.get()
    context['lmeta'] = GlobalMeta.objects.filter(title="Contact")
    context['gmeta'] = GlobalMeta.objects.filter(title="Global")

    return render(request, 'contact.html', context)


def globalmeta(request, context={}):
   try:
       globalmeta = GlobalMeta.objects.get(pk=1)
   except GlobalMeta.DoesNotExist:
       globalmeta = False
   context['globalmeta'] = globalmeta

client/views.py
from django.shortcuts import render

# Create your views here.

news/views.py
from django.shortcuts import render

# Create your views here.

slider/views.py
from django.shortcuts import render

# Create your views here.

templates/armada/about.html
<!--
      about us block
-->
{% if about %}
    <section class="about-us">
       <div class="bg"></div>
       <div class="container">
          <div class="row">

             <div class="col-md-6">
                <!-- <img src="{{ about.image.url }}" height="107" width="411"> -->
                <img src="/media/uploads/armada/about/logo-2.png"  height="107" width="411" >
                <h4>{{ about.title }}</h4>
                 <p>{{ about.text|safe }}</p>
                <a href="#">Подробнее</a>
             </div>

          </div>
       </div>
    </section>
{% endif %}

templates/armada/answer.html
<!--
      answer block
-->
{% if answer %}
    <section class="answer">
       <div class="bg"></div>
       <div class="container">
          <div class="row">

             <div class="col-md-6 col-md-offset-6">
                <img src="{{ answer.image.url }}" height="107" width="411">
                <h4>{{ answer.title }}</h4>
                <p>{{ answer.text|safe }}</p>
                <a href="/blog/{{ answer.slug }}/">Подробнее</a>
             </div>

          </div>
       </div>
    </section>
{% endif %}

templates/armada/clients.html
<!--
      clients block
-->
<section class="clients">
   <div class="container">
      <div class="row">
         <h3>Наши последние клиенты</h3>
         {% if clients %}
            <ul>
                {% for client in clients %}
                   <li><a href="http://{{ client.url }}"><img src="{{ client.image.url }}" alt=""></a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Пока нет клиентов</p>
        {% endif %}
      </div>
   </div>
</section>

templates/armada/index.html
{% extends 'base.html' %}

{% block content %}
    {% include 'armada/slider.html' %}
    {% include 'armada/videoblock.html' %}
    {% include 'armada/about.html' %}
    {% include 'armada/offer.html' %}
    {% include 'armada/answer.html' %}
    {% include 'armada/clients.html' %}
    {% include 'armada/reviews.html' %}
    {% include 'armada/news.html' %}
    {% include 'armada/social.html' %}
{% endblock %}

templates/armada/news.html
<!--
      news block
-->

<section class="news">
   <div class="container">
      <div class="row">
         <div class="col-md-4 col-md-offset-1">
            <h3 class="purple">Новости</h3>
             {% if news %}
                 {% for new in news %}
                    <div class="item">
                        <span>{{ new.created }}</span>
                        <h6><a href="{% url 'armada:news_detail' new.slug%}">{{ new.title|title }}</a></h6>
                        <p>{{ new.text|truncatechars:150|safe }}</p>
                    </div>
                 {% endfor %}
{#                <a href="{% url 'armada:news_list'%}" class="load-more">Еще статьи</a>#}
             {% else %}
                <p>Пока нет новостей</p>
             {% endif %}
         </div>
         <div class="col-md-4 col-md-offset-2">
            <h3 class="yellow">Блог</h3>
             {% if blogs %}
                 {% for blog in blogs %}
                    <div class="item">
                       <span>{{ blog.created }}</span>
                       <h6><a href="{% url 'armada:blogs_detail' blog.slug %}">{{ blog.title|title }}</a></h6>
                       <p>{{ blog.text|safe|truncatechars_html:150 }}</p>
                    </div>
                 {% endfor %}
{#                 <a href="{% url 'armada:blogs_list' %}" class="load-more">Еще статьи</a>#}
             {% else %}
                <p>Нет записей в блоге</p>
             {% endif %}
         </div>
      </div>
   </div>
</section>

templates/armada/offer.html
<!--
      offer block
-->

<section class="offer">
   <div class="container">
      <div class="row">

         <h3>Мы знаем, что предложить!</h3>
         <ul>
             {% if offers %}
                 {% for offer in offers %}
            <li>
               <img src="{{ offer.image.url }}" height="100%" width="58" alt="">
               <h5>{{ offer.title }}</h5>
               <p>{{ offer.text }}</p>
            </li>
                 {% endfor%}

         {% else %}
                <li>
               <p>Нет предложений</p>
            </li>
         </ul>
        {% endif %}
      </div>
   </div>
</section>

templates/armada/reviews.html
<!--
      reviews block
-->

<section class="reviews">
   <div class="container">
      <div class="row">
        {% if reviews %}
         <h3>Наши клиенты о нас</h3>
         <div id="myCarousel1" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
                {% for review in reviews %}
                    <div class="item {% if forloop.counter == 1 %}active{% endif %}">
                       <div class="col-md-8 col-md-offset-2">
                          <h5>{{ review.title }}</h5>
                          <span>{{ review.company }}</span>
                          <p>{{ review.text }}</p>
                       </div>
                    </div><!-- item end -->
                {% endfor %}

            </div><!-- Wrapper for slides -->

            <a class="left carousel-control" href="#myCarousel1" role="button" data-slide="prev"></a>
            <a class="right carousel-control" href="#myCarousel1" role="button" data-slide="next"></a>
            <!-- Left and right controls end -->

         </div><!-- #myCarousel1 end -->
        {% else %}
          <h3>Пока нет отзывов</h3>
        {% endif %}
      </div>
   </div>
</section>

templates/armada/slider.html
<!--
      slider block
-->
{% if sliders %}
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
       <div class="container">
          <ol class="carousel-indicators">
              {% for slider in sliders %}
                <li data-target="#myCarousel" data-slide-to="{{ forloop.counter|add:'-1' }}" {% if forloop.counter == 1 %}class="active"{% endif %}><img src="{{ slider.icon.url }}"></li>
              {% endfor %}
          </ol><!-- Indicators end -->

          <div class="carousel-inner" role="listbox">
            {% for slider in sliders %}
                <div class="item {% if forloop.counter == 1 %}active{% endif %}">
                   <div class="container">
                      <div class="col-md-5 col-md-offset-1 ">
                         <h2>{{ slider.title|title }}</h2>
                         <p>{{ slider.text }}</p>
                      </div>
                      <div class="col-md-5"><img src="{{ slider.image.url }}" height="174" width="561" alt="Chania"></div>
                   </div>
                </div>
            {% endfor %}
          </div><!-- carousel-inner end -->

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"></a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"></a>
       </div>
    </div><!-- carousel end -->
{% endif %}

templates/armada/social.html
<!--
      social block
-->

<section class="social">
   <div class="container">
      <div class="row">
         <div class="col-md-6">
            <p>Будьте в курсе всех событий и новостей</p>
            <h5>Подписывайтесь!</h5>
         </div>
          {% if socials %}
         <ul class="col-md-6">
            {% for social in socials %}
                <li><a href="{{ social.url }}"><img src="{{ social.image.url }}" height="70" width="70" alt=""></a></li>
             {% endfor %}
         </ul>
          {% endif %}
      </div>
   </div>
</section>

templates/armada/videoblock.html
<!--
      video block
-->

<section class="video">
   <div class="container">
      <div class="row">

         <div class="col-md-6 col-md-offset-3">
            <h3>Видео презентация наших работ</h3>
            <p>Lorem ipsum dolor sit amet, an erat tritani interpretaris mel. Erat putant tincidunt his at, inani doming has at. In nobis homero invidunt his. Adhuc forensibus omittantur vis te, duo et putant facilisis, scripta assueverit nam at.</p>
         </div>
         <div class="clear"></div>
         <div class="video-wrapper">
            <iframe width="368" height="277" src="https://www.youtube.com/embed/lCWfVgf2ZAo" frameborder="0" allowfullscreen></iframe>
         </div>

      </div>
   </div>
</section>