armadaLocal/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^feedback/', include('backcall.urls')),
    url(r'^', include('armada.urls')),
    url(r'^uslugi/', include('services.urls')),
    url(r'^zakonodatelsvo/', include('law.urls')),
    url(r'^magazin/', include('shop.urls')),
    url(r'^sozdanie-sajta/', include('sitecreate.urls')),
    url(r'^portfolio/', include('portfolio.urls')),

]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

law/urls.py
# coding: utf8

from django.conf.urls import url
from . import views
app_name = 'law'

urlpatterns = [
    url(r'^$', views.index , name = 'index_law'),
]

services/urls.py
# coding: utf8

from django.conf.urls import url
from . import views
app_name = 'services'

urlpatterns = [
    url(r'^$', views.index , name = 'index_services'),
    url(r'^(?P<slug>[-_\w]+)/$', "services.views.service_detail_view", name='detail'),
]

services/models.py
# coding:utf8
from __future__ import unicode_literals
import random, os
from django.utils.translation import ugettext_lazy as _
from django.db import models
from froala_editor.fields import FroalaField



# Create your models here.

def make_upload_path(instance, filename, prefix = False):
    name, ext = 'image', os.path.splitext(filename)[1]
    n1 = random.randint(0, 1000)
    n2 = random.randint(0, 1000)
    n3 = random.randint(0, 1000)
    filename = str(n1)+'_'+str(n2)+'_'+str(n3)+'.'+ext
    return '%s/%s' %('uploads/project/images', filename)

class About(models.Model):
    title = models.CharField(max_length = 50, verbose_name = _('Title'))
    slug = models.SlugField(max_length = 55, verbose_name = _('Slug'))
    image = models.ImageField(upload_to = 'uploads/services')
    text = models.TextField()
    bold_text = models.TextField()
    attach = models.FileField(upload_to = 'uploads/services/attach')
    attach_img = models.ImageField(upload_to = 'uploads/services/attach_img', default= False)


    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'service_about'
        verbose_name = _('About')
        verbose_name_plural = _('About_servise')

class Category(models.Model):
    title = models.CharField(max_length = 100, verbose_name = _('Title'))
    slug = models.SlugField(max_length = 55, verbose_name = _('Slug'), unique=True)
    icon = models.ImageField(upload_to = 'uploads/services/icons')
    text = FroalaField(verbose_name = _('Text'))
    tdc = models.TextField(verbose_name = _('Title_tdc'))
    time = models.CharField(max_length = 200, verbose_name = _('Time'))
    cost = models.CharField(max_length = 200, verbose_name = _('Cost'))


    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Cat_servise')

class Image(models.Model):
    title = models.CharField(max_length = 255, blank = True, verbose_name = _('Title'))
    image = models.ImageField(upload_to = 'uploads/project/images', blank = True, verbose_name = _('Image'))
    project = models.ForeignKey(Category, blank = True, related_name = 'project1', verbose_name = _('Project'))

    def pic(self):
        if self.image:
            return '<img src="%s" width="70">' %self.image.url
        else:
            return '(none)'
    pic.short_description = _('Big Image')
    pic.allow_tags = True

    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'project_images'
        verbose_name = _('Image')
        verbose_name_plural = _('Project Images')

services/views.py
from django.shortcuts import render, render_to_response
from django.http import Http404
from django.template.context_processors import csrf

from .models import About, Category, Image
from django.views import generic
from armada.models import Contact, Address, FooterInfo, GlobalMeta, LocalMeta, Offer, Social
# Create your views here.


def service_detail_view(request, context={}, slug=""):
    context.update(csrf(request))
    context['images'] = Image.objects.all()
    context['contacts'] = Contact.objects.all()
    context['addresses'] = Address.objects.all()
    context['finfo'] = FooterInfo.objects.get()
    context['socials'] = Social.objects.all()
    context['offers'] = Offer.objects.all()
    context['lmeta'] = LocalMeta.objects.filter(service__slug=slug)
    try:
        cats = Category.objects.get(slug=slug)
    except Category.DoesNotExist:
        cats = False
    context['cats'] = cats
    return render_to_response('services/detail.html', context)

def index(request, context = {}):
    context.update(csrf(request))
    try:
        abouts = About.objects.all()
    except About.DoesNotExist:
        abouts = False
    context ['abouts'] = abouts
    try:
        finfo = FooterInfo.objects.get()
    except FooterInfo.DoesNotExist:
        finfo = False
    context ['finfo'] = finfo
    try:
        address = Address.objects.all()
    except Address.DoesNotExist:
        address = False
    context['addresses'] = address
    try:
        contact = Contact.objects.all()
    except Contact.DoesNotExist:
        contact = False
    context['contacts'] = contact

    try:
        cats = Category.objects.all()
    except Category.DoesNotExist:
        cats = False
    context ['cats'] = cats
    context['lmeta'] = GlobalMeta.objects.filter(title="Service")
    context['gmeta'] = GlobalMeta.objects.filter(title="Global")
    context['offers'] = Offer.objects.all()
    context['socials'] = Social.objects.all()


    return render(request, 'services/index.html', context)



# class DetailView(generic.DetailView):
#     model = Category
#     template_name = 'services/detail.html'
#     context_object_name = 'cats'
#
#     def get_context_data(self, *args, **kwargs):
#         context = super(DetailView, self).get_context_data(**kwargs)
#         context['images'] = Image.objects.all()
#         context['contacts'] = Contact.objects.all()
#         context['addresses'] = Address.objects.all()
#         context['finfo'] = FooterInfo.objects.get()
#         context['lmeta'] = LocalMeta.objects.filter(service__slug=slug)
#
#         return context

templates/services/detail.html
{% extends 'services/index.html' %}

{% load staticfiles %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb cats.title "Услуги" "detail" %}
{% endblock %}




{% block content %}
{% render_breadcrumbs 'bread.html'%}

<section class="service-category">
   <div class="container">
      <div class="row">
        {% if cats %}
         <div class="col-md-6 left-side">
            <h1>{{ cats.title|safe }}</h1>
            <p>{{ cats.text|safe }}<p>
         </div>
         <div class="col-md-6 right-side">
            <h2>{{ cats.tdc|safe }}</h2>
             <p>Скроки и стоимость работ указаны не точные и могут изменяться в как в положительную сторону, так и в отрицательную</p>
             <ul>
               <li>
                  <img src="{%static 'static/img/png/time.png'%}" height="50" width="50">
                  <p>Время:</p>
                  <span>{{ cats.time }}</span>
               </li>
               <li>
                  <img src="{%static 'static/img/png/financa.png'%}" height="50" width="50">
                  <p>Стоимость:</p>
                  <span>{{ cats.cost }}</span>
               </li>
            </ul>
            <a href="" data-toggle="modal" data-target="#myModal">Заказать {{ cats.title }}</a>
         </div>
        {% endif  %}
      </div>
   </div>
</section>



<!--
      slider block
-->
{% if images %}
<div id="myCarousel" class="carousel service-category-slider slide" data-ride="carousel">
   <div class="container">

      <div class="carousel-inner" role="listbox">

          {% for image in images %}
         <div class="item {% if forloop.counter == 1 %} active{% endif %}">
            <h3>{{ image.title|title }}</h3>
            <img src="{{ image.image.url }}" alt="">
         </div>
          {% endfor %}

      </div><!-- carousel-inner end -->

      <ol class="carousel-indicators">
      {% for image in images %}
         <li data-target="#myCarousel" data-slide-to="{{ forloop.counter|add:'-1' }}" {% if forloop.counter >= 1 %}class="active">{% endif %}<img src="{{ image.image.url }}"></li>
      {% endfor %}
      </ol><!-- Indicators end -->

   </div>

</div><!-- carousel end -->
{% endif %}

    <section class="offer">
   <div class="container">
      <div class="row">

         <h3>Мы знаем, что предложить!</h3>
         <ul>
             {% if offers %}
                 {% for offer in offers %}
            <li>
               <img src="{{ offer.image.url }}" height="100%" width="58" alt="">
               <h5>{{ offer.title }}</h5>
               <p>{{ offer.text }}</p>
            </li>
                 {% endfor%}

         {% else %}
                <li>
               <p>Нет предложений</p>
            </li>
         </ul>
        {% endif %}
      </div>
   </div>
</section>


   </div>

    <section class="social">
   <div class="container">
      <div class="row">
         <div class="col-md-6">
            <p>Будьте в курсе всех событий и новостей</p>
            <h5>Подписывайтесь!</h5>
         </div>
          {% if socials %}
         <ul class="col-md-6">
            {% for social in socials %}
                <li><a href="{{ social.url }}"><img src="{{ social.image.url }}" height="70" width="70" alt=""></a></li>
             {% endfor %}
         </ul>
          {% endif %}
      </div>
   </div>
</section>
{% endblock %}

templates/services/index.html
{% extends 'base.html' %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}

    {{ block.super }}
    {% breadcrumb "Услуги" "index_services" %}

{% endblock %}



{% block content %}

    {% render_breadcrumbs 'bread.html'%}


<section class="outdoor-page-content">
   <div class="container">
      <div class="row">
        {% if abouts %}
            {% for a in abouts %}
         <div class="col-md-6">
            <div class="row">
               <img src="{{ a.image.url }}" alt="" title="">
            </div>
         </div>
         <div class="col-md-5">
            <div class="row">
               <h1>{{ a.title }}</h1>
               <p>{{ a.text | safe }}</p>
               <h2>{{ a.bold_text | safe }}</h2>
            </div>
         </div>

         <div class="clear"></div>
        {% if cats %}
            {% for cat in cats %}
                <ul>
                   <li>
                      <div class="img-wrapper">
                      <img src="{{ cat.icon.url }}" alt=""></div>
                      <p><a href= "{% url 'services:detail' cat.slug %}">{{ cat.title }}</a></p>
                   </li>
                </ul>
            {% endfor %}
        {% endif %}

            {% endfor %}
      {% endif %}
      </div>
   </div>


</section>

<!--
  price-list block
-->

{% if abouts %}
    {% for a in abouts %}
<section class="price-list">
               <div class="container">
                  <div class="row">
                     <a href="{{ a.attach.url }}" class="img-wrapper"><img src="{{ a.attach_img.url }}"></a>
                     <a href="{{ a.attach.url }}"><span>Скайте прайс лист</span></a>
                  </div>
               </div>
</section>
 {% endfor %}
      {% endif %}



    <section class="offer">
   <div class="container">
      <div class="row">

         <h3>Мы знаем, что предложить!</h3>
         <ul>
             {% if offers %}
                 {% for offer in offers %}
            <li>
               <img src="{{ offer.image.url }}" height="100%" width="58" alt="">
               <h5>{{ offer.title }}</h5>
               <p>{{ offer.text }}</p>
            </li>
                 {% endfor%}

         {% else %}
                <li>
               <p>Нет предложений</p>
            </li>
         </ul>
        {% endif %}
      </div>
   </div>
</section>


   </div>

    <section class="social">
   <div class="container">
      <div class="row">
         <div class="col-md-6">
            <p>Будьте в курсе всех событий и новостей</p>
            <h5>Подписывайтесь!</h5>
         </div>
          {% if socials %}
         <ul class="col-md-6">
            {% for social in socials %}
                <li><a href="{{ social.url }}"><img src="{{ social.image.url }}" height="70" width="70" alt=""></a></li>
             {% endfor %}
         </ul>
          {% endif %}
      </div>
   </div>
</section>

{% endblock %}