armada/urls.py
# coding: utf8

from django.conf.urls import url
from . import views


app_name = 'armada'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),

    url(r'^news/(?P<slug>[-_\w]+)/$', 'armada.views.news_detail_view', name='news_detail'),

    url(r'^blog/(?P<slug>[-_\w]+)/$', 'armada.views.blog_detail_view', name='blogs_detail'),
    url(r'^news/', 'armada.views.news_list_view', name='news_list'),
    url(r'^blog/', 'armada.views.blog_list_view', name='blogs_list'),
    url(r'^contact/', views.contact, name='contact'),



]

armadaLocal/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^feedback/', include('backcall.urls')),
    url(r'^', include('armada.urls')),
    url(r'^uslugi/', include('services.urls')),
    url(r'^zakonodatelsvo/', include('law.urls')),
    url(r'^magazin/', include('shop.urls')),
    url(r'^sozdanie-sajta/', include('sitecreate.urls')),
    url(r'^portfolio/', include('portfolio.urls')),

]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

law/urls.py
# coding: utf8

from django.conf.urls import url
from . import views
app_name = 'law'

urlpatterns = [
    url(r'^$', views.index , name = 'index_law'),
]

portfolio/urls.py
# coding: utf8

from django.conf.urls import url
from . import views
app_name = 'portfolio'

urlpatterns = [
    url(r'^$', views.index , name = 'index_portfolio'),
]

services/urls.py
# coding: utf8

from django.conf.urls import url
from . import views
app_name = 'services'

urlpatterns = [
    url(r'^$', views.index , name = 'index_services'),
    url(r'^(?P<slug>[-_\w]+)/$', "services.views.service_detail_view", name='detail'),
]

shop/urls.py
# coding: utf8

from django.conf.urls import url
from . import views
app_name = 'shop'

urlpatterns = [
    url(r'^$', views.index , name = 'index_shop'),
]

templates/base.html
<!DOCTYPE html>
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {% breadcrumb "Главная" "/" %}
{% endblock %}
<html lang="en">
<head>
    {% block meta %}
    {% include 'meta.html' %}
    {% endblock %}
</head>
<body>
    {% include 'header.html' %}
    {% block content %}
        {% render_breadcrumbs 'bread.html'%}

    {% endblock %}

    {% include 'footer.html' %}
</body>
</html>

templates/bread.html
<div class="breadcrumbs">
   <div class="container">
         <ul>
         {% for url, label in breadcrumbs %}
            <li>{% ifnotequal forloop.counter breadcrumbs_total %}<a href="{{ url }}">{{ label|safe }}</a></li>
             {% else %}
             {{ label|safe }}
              {% endifnotequal %}
         {% endfor %}
         </ul>
   </div>
</div>

templates/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Контакты" "contact" %}
{% endblock %}



{% block content %}
    {% render_breadcrumbs 'bread.html' %}


    <section class="contacts-page">
   <div class="container">
      <div class="row">

         <div class="col-md-5">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2924.925467712579!2d74.60812695129526!3d42.853306911698624!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDLCsDUxJzExLjkiTiA3NMKwMzYnMzcuMiJF!5e0!3m2!1sru!2sru!4v1455712420511" width="100%" height="325" frameborder="0" style="border:0" allowfullscreen></iframe>
         </div>

         <div class="col-md-5">
            <h1>Контакты</h1>
            <p><img src="{% static 'static/img/png/contacts-page/1.png'%}" height="30" width="22" alt=""><span>Байтик- Батыра 23а</span></p>
            <p><img src="{%static 'static/img/png/contacts-page/2.png' %}" height="29" width="16" alt=""><span>0312 475 107,&emsp; 0312 477 594<br>
0553 577 575<br>
0700 477 594&emsp; 0703 756 525<br>
0771 360 905</span></p>
            <p class="last"><img src="{%static 'static/img/png/contacts-page/3.png'%}" height="19" width="26" alt=""><span>armada.kg@gmail.com</span></p>

            <form>
               <input type="text" placeholder="Имя">
               <input type="email" placeholder="E-mail">
               <textarea></textarea>
               <input type="submit" value="Отправить">
            </form>
         </div>


      </div>

       <section class="offer">
   <div class="container">
      <div class="row">

         <h3>Мы знаем, что предложить!</h3>
         <ul>
             {% if offers %}
                 {% for offer in offers %}
            <li>
               <img src="{{ offer.image.url }}" height="100%" width="58" alt="">
               <h5>{{ offer.title }}</h5>
               <p>{{ offer.text }}</p>
            </li>
                 {% endfor%}

         {% else %}
                <li>
               <p>Нет предложений</p>
            </li>
         </ul>
        {% endif %}
      </div>
   </div>
</section>


   </div>

    <section class="social">
   <div class="container">
      <div class="row">
         <div class="col-md-6">
            <p>Будьте в курсе всех событий и новостей</p>
            <h5>Подписывайтесь!</h5>
         </div>
          {% if socials %}
         <ul class="col-md-6">
            {% for social in socials %}
                <li><a href="{{ social.url }}"><img src="{{ social.image.url }}" height="70" width="70" alt=""></a></li>
             {% endfor %}
         </ul>
          {% endif %}
      </div>
   </div>
</section>
</section>



{% endblock %}

templates/footer.html
<footer>
    {% load staticfiles %}
   <div class="container">
      <div class="row">

         <div class="col-md-4">
             {% if finfo %}
            <a href="/" class="logo"><img src="{{ finfo.image.url }}" height="107" width="411"></a>
            <p>{{ finfo.text| safe }}</p>
            <p>CP © 2012-{{ finfo.created}} Armada.kg. Все права защищены.</p>
            <h6>{{ finfo.created_by }}<a href="http://googstudio.com" target="_blank"><img src="{{ finfo.logo.url }}" height="43" width="81"></a></h6>
            {% else %}
                 Нет записи!
            {% endif %}
         </div>

         <div class="col-md-4 middle">
            <h4>Контакты</h4>
            {% if contacts %}
                {% for contact in contacts %}
                    <span class="contacts-icon"><img src="{{ contact.image.url }}">{{ contact.phone }}</span>
                {% endfor %}
            {% endif %}
         {% if addresses %}
            <p>
             {% for address in addresses %}
                {% if forloop.counter == 1 %}
                    {{ address.address }}<br>
                 {% else %}
                    {{ address.address }}
                 {% endif %}
             {% endfor %}
         {% endif %}

         </p>
         </div>
         <div class="col-md-4 right-side">
            <h4>Свяжитесь с нами</h4>
            <span>Мы ответим на любые интерисующие вопросы!</span>
            <form id="feedback" action="/feedback/send">
                {% csrf_token %}
               <input type="text" placeholder="Имя" name="name">
               <input type="email" placeholder="Email" name="email">
               <textarea name="text"></textarea>
               <input type="submit" value="Отправить" id="send">
            </form>
         </div>
        <script>
            $(function(){
                $('#send').click(function(e){
                    e.preventDefault()
                    $.ajax({
                        url : '/feedback/send',
                        method : 'post',
                        data : $('form#feedback').serialize(),
                        success : function(res){
                            alert(res)
                        }
                    });
                });
            })
        </script>
      </div>
   </div>
</footer>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
         <h4 class="modal-title">Оставьте заявку и наш менеджер свяжется с вами!</h4>
      </div>
      <div class="modal-body">
        <form id="call" action="call/send">
            {% csrf_token %}
           <input type="text" name="name" placeholder="Введите свое Имя">
           <input type="text" name="phone" placeholder="Введите свой телефон">
            {% if cats %}
            <input type="text" name="service" value="{{ cats.title }}">
            {% endif %}
           <div class="clearfix"></div>
           <input type="submit" value="Заказать звонок" id="send1">
        </form>
      </div>
    <script>
       $(function(){
    $('#send1').click(function(e){
        e.preventDefault();
        $.ajax({
            data: $('form').serialize(),
            url: '/feedback/call/',
            method: 'post',
            success: function(res){
                alert(res)
            }
        })
    })
});
        </script>
    </div>
  </div>
</div>

templates/header.html
<!--
      header block
-->
{% load staticfiles %}
<header>
   <div class="container">
      <div class="row">
					
				<div class="col-sm-6 col-xs-12">
         	<div class="navbar-header">
           	 <h1><a href="/" class="logo" alt="Armada" title="Armada"><img src="{% static 'static/logo.png' %}" height="61" width="58" alt="Armada" title="Armada"><span>Рекламно - производственная<br>компания</span></a></h1><!-- logo -->
         	</div><!-- .navbar-header end -->
				</div>

				<div class="col-sm-6">
         <a href="mailto:armada.kg@gmail.com" alt="Напишите нам" title="Напишите нам" class="pull-right">armada.kg@gmail.com</a>
				</div>
      </div><!-- .row end -->
   </div><!-- .container end -->
</header>

<!--
      nav block
-->

<nav class="navbar navbar-default" role="navigation">
	<div class="container">
		<div class="row">

			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div><!-- .navbar-header end -->

			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav b-nav_1">
					<li><a href="/">Главная</a></li>
					<li><a href="{% url 'services:index_services' %}">УСЛУГИ</a></li>
					<li><a href="{% url 'shop:index_shop' %}">МАГАЗИН</a></li>
                    <li><a href="{% url 'sitecreate:index_site' %}">СОЗДАНИЕ САЙТОВ</a></li>
                    <li><a href="{% url 'portfolio:index_portfolio' %}">Портфолио</a></li>
                    <li><a href="{% url 'law:index_law' %}">Законодательство</a></li>
                    <li><a href="{% url 'armada:blogs_list' %}">Блог</a></li>
                    <li><a href="{% url 'armada:news_list' %}">Новости</a></li>
                    <li><a href="{% url 'armada:contact' %}">Контакты</a></li>
                    <a href="" class="order-btn" data-toggle="modal" data-target="#myModal">Заказать звонок</a>
				</ul><!-- ul.nav end -->
			</div><!--.collapse end -->

		</div><!-- .row end -->
	</div><!-- .container end -->
</nav>

templates/meta.html
{% load staticfiles %}
    {% if lmeta %}
        {% for item in lmeta %}
    <meta name="title" content="{{ item.meta_title }}">
    <meta name="description" content="{{ item.meta_desc }}">
    <meta name="keywords" content="{{ item.meta_key }}" >
        {% endfor %}
    {% else %}
        {% for item in gmeta %}
    <meta name="title" content="{{ item.meta_title }}">
    <meta name="description" content="{{ item.meta_desc }}">
    <meta name="keywords" content="{{ item.meta_key }}" >
        {% endfor %}
        {% endif %}

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% if lmeta %}
{% for item in lmeta %}
<title>{{ item.meta_title }}</title>
{% endfor %}
{% else %}
    {% for item in gmeta %}
<title>{{ item.meta_title }}</title>
    {% endfor %}
{% endif %}
<link href="{% static 'static/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'static/css/ekko-lightbox.min.css' %}" rel="stylesheet">
<link href="{% static 'static/css/reset.css' %}" rel="stylesheet">
<link href="{% static 'static/css/fonts.css' %}" rel="stylesheet">
<link href="{% static 'static/css/style.css' %}" rel="stylesheet">
<!-- <link href="{% static 'static/css/style.less' %}" rel="stylesheet"> -->
<link href="{% static 'static/css/media.css' %}" rel="stylesheet">
<!-- Заглушка на старые браузеры -->
<!--[if IE 8]>
   <script>
      window.location = "oldbrowser/index.html";
   </script>
<![endif]-->
	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>	<![endif]-->

<!-- Bootstrap core JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="{% static 'static/js/bootstrap.min.js' %}"></script>
<script src="{% static 'static/js/ekko-lightbox.min.js' %}"></script>
<script src="{% static 'static/js/custom.js' %}"></script>